# String
server:
  port: 8081
# Security
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
# Util
tungbt:
  telegrambot:
    token: 5721621056:AAGGG-1J2nrI7BInxui4dSpElcwLCynB1Kg